name: Bug report
description: Create a report to help us improve
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please search for existing issues before creating a new one. If you find a matching issue, please add a comment with additional information instead of creating a new issue.
        If you are looking for help or have a question, please use [Discussions](https://github.com/CycloneDX/cyclonedx-gradle-plugin/discussions)
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Self-contained Reproducer Project
      description: |
        Provide a [minimal, self-contained example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) project demonstrating the problem as a GitHub repository or an attached archive.
        You can use [the template](https://github.com/gradle/gradle-issue-reproducer) with a Gradle GitHub action set up to showcase your problem.
        In the rare cases where this is infeasible, we will also accept a detailed set of instructions.
        You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: build-scan-url
    attributes:
      label: Gradle build scan URL (optional)
      description: |
        You can run your build command with `--scan` to publish a Build Scan to [scans.gradle.com](https://scans.gradle.com/).
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. Linux
    validations:
      required: false
  - type: input
    id: gradle_version
    attributes:
      label: Gradle version
      description: e.g. 8.10
    validations:
      required: false
  - type: input
    id: plugin_version
    attributes:
      label: CycloneDX Plugin version
      description: e.g. 1.9.0
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to provide a fix
        - label: I will wait until somebody else fixes it

