name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please search for existing issues before creating a new one. If you find a matching issue, please add a comment with additional information instead of creating a new issue.
        If you are looking for help or have a question, please use [Discussions](https://github.com/CycloneDX/cyclonedx-gradle-plugin/discussions)
  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to provide an implementation
        - label: I will wait until somebody else implements it
