name: Gradle update

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'CycloneDX/cyclonedx-gradle-plugin' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # v2.1.0
        with:
          labels: gradlew,technical-debt
